web:
  build: .
  env_file: .env
  command: gunicorn talkdesign.wsgi --log-file -
  volumes:
    - .:/app/user
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
shell:
  build: .
  env_file: .env
  command: bash
  volumes:
    - .:/app/user
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
